# Generated by Django 4.1.13 on 2024-09-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('job_stream', models.CharField(blank=True, max_length=255)),
                ('workstation', models.CharField(blank=True, max_length=255)),
                ('first_responsible', models.CharField(blank=True, max_length=255)),
                ('second_responsible', models.CharField(blank=True, max_length=255)),
                ('third_responsible', models.CharField(blank=True, max_length=255)),
                ('activation_time', models.CharField(blank=True, max_length=255)),
                ('criticality', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
