# Generated by Django 5.1.1 on 2024-10-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cc_server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=255)),
                ('server_cliente', models.CharField(max_length=255)),
                ('datacenter', models.CharField(max_length=255)),
                ('plataforma', models.CharField(default='unknown', max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('criticidade', models.CharField(default='unknown', max_length=255)),
                ('responsabilidade', models.CharField(default='unknown', max_length=255)),
                ('storage', models.CharField(default='unknown', max_length=255)),
                ('os', models.CharField(default='unknown', max_length=255)),
                ('escalonamento1', models.CharField(default='unknown', max_length=255)),
                ('escalonamento2', models.CharField(default='unknown', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('job_stream', models.CharField(blank=True, max_length=255, null=True)),
                ('workstation', models.CharField(blank=True, max_length=255, null=True)),
                ('aplicacao', models.CharField(blank=True, max_length=255, null=True)),
                ('first_responsible', models.CharField(blank=True, max_length=255, null=True)),
                ('second_responsible', models.CharField(blank=True, max_length=255, null=True)),
                ('third_responsible', models.CharField(blank=True, max_length=255, null=True)),
                ('activation_time', models.CharField(blank=True, max_length=255, null=True)),
                ('criticality', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
