# Generated by Django 5.1.1 on 2024-09-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=255)),
                ('server_cliente', models.CharField(max_length=255)),
                ('datacenter', models.CharField(max_length=255)),
                ('plataforma', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('criticidade', models.CharField(max_length=255)),
                ('responsabilidade', models.CharField(max_length=255)),
                ('escalonamento1', models.CharField(max_length=255)),
                ('escalonamento2', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'servers',
            },
        ),
    ]
