# Generated by Django 5.1.1 on 2024-10-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_server'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='descricao',
        ),
        migrations.AddField(
            model_name='job',
            name='ferramenta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='os',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='storage',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='criticidade',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='datacenter',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='escalonamento1',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='escalonamento2',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='plataforma',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='responsabilidade',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_cliente',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_name',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterModelTable(
            name='server',
            table=None,
        ),
    ]
