# Generated by Django 5.1.1 on 2024-10-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_cc_fast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cc_fast',
            name='criticidade',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='cc_fast',
            name='datacenter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cc_fast',
            name='escalonamento1',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='cc_fast',
            name='escalonamento2',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='cc_fast',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cc_fast',
            name='os',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='cc_fast',
            name='plataforma',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='cc_fast',
            name='responsabilidade',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='cc_fast',
            name='server_cliente',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cc_fast',
            name='server_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cc_fast',
            name='storage',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='cc_server',
            name='criticidade',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='cc_server',
            name='datacenter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cc_server',
            name='escalonamento1',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='cc_server',
            name='escalonamento2',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='cc_server',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cc_server',
            name='os',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='cc_server',
            name='plataforma',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='cc_server',
            name='responsabilidade',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='cc_server',
            name='server_cliente',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cc_server',
            name='server_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cc_server',
            name='storage',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
