# Generated by Django 5.1.1 on 2024-10-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_description_job_descricao_job_ferramenta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='descricao',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='server',
            name='datacenter',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_cliente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_name',
            field=models.CharField(max_length=255),
        ),
    ]
