# Generated by Django 5.1.1 on 2024-10-02 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_activation_time_alter_job_criticality_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='descricao',
        ),
    ]
