# Generated by Django 5.1.1 on 2024-10-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=255)),
                ('modelo', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('descricao', models.CharField(blank=True, default='unknown', max_length=255)),
                ('local', models.GenericIPAddressField(blank=True, null=True)),
                ('fornecedor_manut', models.CharField(blank=True, default='unknown', max_length=255)),
                ('data_inicial_manut', models.DateField(blank=True, null=True)),
                ('data_final_manut', models.DateField(blank=True, null=True)),
                ('meses_contratados', models.CharField(blank=True, default='unknown', max_length=255)),
                ('dias_para_termino', models.IntegerField(blank=True, default=0, null=True)),
                ('status_contrato', models.CharField(blank=True, default='unknown', max_length=255)),
                ('brand', models.CharField(blank=True, default='unknown', max_length=255)),
                ('end_datacenter', models.CharField(blank=True, default='unknown', max_length=255)),
                ('rack', models.CharField(blank=True, default='unknown', max_length=255, null=True)),
                ('storage', models.CharField(blank=True, default='unknown', max_length=255, null=True)),
                ('ip', models.CharField(blank=True, default='unknown', max_length=255)),
                ('alerta', models.CharField(blank=True, default='unknown', max_length=255)),
            ],
            options={
                'verbose_name': 'Hardware',
                'verbose_name_plural': 'Hardwares',
            },
        ),
    ]
