# Generated by Django 5.1.1 on 2024-10-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Servidores_CC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(blank=True, max_length=255)),
                ('server_cliente', models.CharField(blank=True, max_length=255)),
                ('datacenter', models.CharField(blank=True, max_length=255)),
                ('plataforma', models.CharField(blank=True, default='unknown', max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criticidade', models.CharField(blank=True, default='unknown', max_length=255)),
                ('responsabilidade', models.CharField(blank=True, default='unknown', max_length=255)),
                ('storage', models.CharField(blank=True, default='unknown', max_length=255)),
                ('os', models.CharField(blank=True, default='unknown', max_length=255)),
                ('ambiente', models.CharField(blank=True, default='hml', max_length=10)),
                ('escalonamento1', models.CharField(blank=True, default='unknown', max_length=255)),
                ('escalonamento2', models.CharField(blank=True, default='unknown', max_length=255)),
                ('descricao', models.CharField(blank=True, default='unknown', max_length=255)),
            ],
            options={
                'verbose_name': 'Servidor CC',
                'verbose_name_plural': 'Servidores CC',
            },
        ),
        migrations.CreateModel(
            name='Servidores_FastShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(blank=True, max_length=255)),
                ('server_cliente', models.CharField(blank=True, max_length=255)),
                ('datacenter', models.CharField(blank=True, max_length=255)),
                ('plataforma', models.CharField(blank=True, default='unknown', max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criticidade', models.CharField(blank=True, default='unknown', max_length=255)),
                ('responsabilidade', models.CharField(blank=True, default='unknown', max_length=255)),
                ('storage', models.CharField(blank=True, default='unknown', max_length=255)),
                ('os', models.CharField(blank=True, default='unknown', max_length=255)),
                ('ambiente', models.CharField(blank=True, default='hml', max_length=10)),
                ('escalonamento1', models.CharField(blank=True, default='unknown', max_length=255)),
                ('escalonamento2', models.CharField(blank=True, default='unknown', max_length=255)),
                ('descricao', models.CharField(blank=True, default='unknown', max_length=255)),
            ],
            options={
                'verbose_name': 'Servidor FastShop',
                'verbose_name_plural': 'Servidores FastShop',
            },
        ),
    ]
