# Generated by Django 5.1.1 on 2024-10-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0001_initial'),  # Altere para a dependência correta
    ]

    operations = [
        migrations.AddField(
            model_name='servidores_cc',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
