# Generated by Django 5.1.1 on 2024-10-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0002_servidores_cc_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidores_cc',
            name='ambiente',
            field=models.CharField(blank=True, default='unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servidores_fastshop',
            name='ambiente',
            field=models.CharField(blank=True, default='unknown', max_length=255, null=True),
        ),
    ]
