# Generated by Django 5.1.1 on 2024-10-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0003_alter_servidores_cc_ambiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidores_fastshop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
